# Generated by Django 4.2.1 on 2023-05-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=30)),
                ("first_name", models.CharField(max_length=30)),
                ("middle_initial", models.CharField(max_length=5)),
                ("sex", models.CharField(max_length=5)),
                ("strand", models.CharField(max_length=10)),
                ("graduation_year", models.IntegerField()),
                ("college_university", models.CharField(max_length=100)),
                ("college_course", models.CharField(max_length=100)),
                ("hei", models.CharField(max_length=10)),
            ],
        ),
    ]
